# Generated by Django 5.0.1 on 2025-11-22 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('purpose', models.CharField(choices=[('PERSONAL', 'Personal Visit'), ('DELIVERY', 'Delivery'), ('SERVICE', 'Service/Repair'), ('OFFICIAL', 'Official'), ('OTHER', 'Other')], default='PERSONAL', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/')),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('IN_PREMISES', 'Inside Premises'), ('EXITED', 'Exited'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('pre_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_approved', to=settings.AUTH_USER_MODEL)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_checked_in', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_checked_out', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='society.flat')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='society.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
