# Generated by Django 5.0.1 on 2025-11-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('MAINTENANCE', 'Maintenance'), ('MEETING', 'Meeting'), ('EVENT', 'Event'), ('BILLING', 'Billing'), ('SECURITY', 'Security'), ('EMERGENCY', 'Emergency')], default='GENERAL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
