# Generated by Django 5.0.1 on 2025-11-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('bhk', models.CharField(default='2BHK', max_length=10)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('occupancy_status', models.CharField(choices=[('OWNER', 'Owner Occupied'), ('TENANT', 'Tenant Occupied'), ('VACANT', 'Vacant')], default='OWNER', max_length=10)),
                ('parking_slots', models.IntegerField(default=0)),
                ('parking_numbers', models.CharField(blank=True, help_text='Comma-separated parking numbers', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['society', 'floor', 'flat_number'],
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('total_flats', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Societies',
                'ordering': ['name'],
            },
        ),
    ]
