# Generated by Django 5.0.1 on 2025-11-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Block A', 'Block B'", max_length=50)),
                ('floors', models.IntegerField(help_text='Number of floors in this block')),
                ('units_per_floor', models.IntegerField(help_text='Number of units per floor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='society.society')),
            ],
            options={
                'ordering': ['society', 'name'],
                'unique_together': {('society', 'name')},
            },
        ),
        migrations.AddField(
            model_name='flat',
            name='block',
            field=models.ForeignKey(blank=True, help_text='Block this flat belongs to (optional for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='society.block'),
        ),
    ]
